### ISSUE TITLE
Improve meta documentation for this repo.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1607]
The `README.md` for this repo is missing some crucial components. This issue tracks:

- [x] Write/improve guide on contributions.
- [x] Add installation instructions to build and run the site locally.
- [ ] Explain how we triage issues in this repo.
- [x] Add stickers showing:
    - [x] License
    - [x] Website status
    - [ ] ~~Backlog~~
    - [x] CI/CD checks
