### ISSUE TITLE
Reorganize `/docs` directory to match website structure.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1798]
The hierarchy of the content in this repo doesn't match the structure of the website. For example, the Quick Start tutorial has the slug `/docs/en/getting-started/quick-start`, but the page is under the Get started section, not `getting-started` as referenced in the slug. On top of that, the markdown itself is located in `docs/en/quick-start.mdx`.

Situations like this make editing, navigating, and maintaining the docs tricky; writers have to do lots of grepping just to find the page that they want to edit.

To rectify this issue, we should move markdown files into the dir structure that is represented on the site, specifically the sidebar. Taking the above example again, we should move `docs/en/quick-start.mdx` to `docs/en/get-started/quick-start.mdx`. Because the URL / slugs of several pages are manually customized, we shouldn't rely on URL structure to define how to organize this repo.

## Tasks

Instead of moving everything around in one go, I suggest we make changes section by section. This issue can act as the root issue, with each section having it's own minor issue and subsequent PR:

Docs:

- [ ] Get started https://github.com/ClickHouse/clickhouse-docs/pull/1799
- [ ] Concepts
- [ ] Guides
- [ ] Integrations
- [ ] Data Formats
- [ ] Clients and Drivers
- [ ] Managing ClickHouse
- [ ] About ClickHouse

Cloud:

- [ ] Get started
- [ ] Managing Cloud
- [ ] Cloud API
- [ ] Cloud Reference
- [ ] Best Practices
- [ ] Security
- [ ] Migrating to Cloud

SQL Reference:

- [ ] Introduction
- [ ] Engines
- [ ] Functions
- [ ] Other Features

Knowlegde Base:

Nothing needs to be changed in here.

**Comment by johnnymatthews** [comment]
This project is on hold until https://github.com/ClickHouse/clickhouse-docs/issues/1833 has concluded.

**Comment by gingerwizard** [comment]
We aren't going to do this, we don't couple disk structure to layout structure. We can reconsider in the future.
