### ISSUE TITLE
Move internal knowledge-base articles into the public knowledge-base.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2137]
We have an internal knowledge-base (KB) that support engineers use and reference to help folks. Some of these internal articles can be moved to the public KB. I'm gonna list these internal articles here, but only folks within the ClickHouse org will be able to view them (other folks with get GitHub's 404 page).

- [x] [Internal KB related to MS technologies](https://github.com/ClickHouse/internal-knowledge-base/issues/297), [alt link](https://github.com/ClickHouse/internal-knowledge-base/issues/273)
- [x] [Importing GeoJSON with a deeply nested object array](https://github.com/ClickHouse/internal-knowledge-base/issues/290)
- [x] [How to connect to CH Cloud using SSH Keys](https://github.com/ClickHouse/internal-knowledge-base/issues/287)
- [x] [How to convert a Map(String, String) to a Map(String,Array(String))](https://github.com/ClickHouse/internal-knowledge-base/issues/286)
- [x] [How do I check compression ratios for my data in ClickHouse](https://github.com/ClickHouse/internal-knowledge-base/issues/238)
- [x] [How to use the ClickHouse neighbor function with timestamps](https://github.com/ClickHouse/internal-knowledge-base/issues/285)
- [x] [How to create a table that can query multiple remote clusters](https://github.com/ClickHouse/internal-knowledge-base/issues/245)

**Comment by linhgiang24** [comment]
@gingerwizard I think we can close this issue.  The only one from the KB list above that's not currently public is the "Importing GeoJSON with a deeply nested object array" one - but it's currently being reviewed and worked on here:  https://github.com/ClickHouse/clickhouse-docs/pull/2926

**Comment by linhgiang24** [comment]
@gingerwizard I'm not sure why most of those where checked when they haven't been pushed to public KB; so I unchecked them.  The three checked items above are public KBs currently. 

We're, at the moment, working on the "Importing GeoJSON with a deeply nested object array" KB.  Details are here:  https://github.com/ClickHouse/clickhouse-docs/pull/2926.

**Comment by gingerwizard** [comment]
Horah!!!
